# Generated by Django 5.0.1 on 2024-02-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
